export const LOGIN_MUTATION = "LOGIN_MUTATION";
export const REGISTER_USER_MUTATION = "REGISTER_USER_MUTATION";
export const SERVICES_REQUESTS_LIST = "SERVICES_REQUESTS_LIST";
export const SERVICE_REQUEST = "SERVICES_REQUESTS_LIST";
export const SERVICES_CATEGORY = "SERVICES_CATEGORY";
export const CREATE_SERVICE_REQUEST = "CREATE_SERVICE_REQUEST";
export const GET_USER_PROFILE = "GET_USER_PROFILE";